sonar.projectKey=calculadora-python-practica
sonar.projectName=Calculadora_Python_Practica
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=test_calculadora.py

sonar.tests=.
sonar.test.inclusions=test_calculadora.py

sonar.sourceEncoding=UTF-8